spring.application.name=api-sistema-venda-carros

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${VENDA_CARROS_DB_URL}
spring.datasource.username=${VENDA_CARROS_DB_USERNAME}
spring.datasource.password=${VENDA_CARROS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
